version: '2'
services:
    prestige-app:
        image: prestige
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://prestige-postgresql:5432/Prestige
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    prestige-postgresql:
        extends:
            file: postgresql.yml
            service: prestige-postgresql
